# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Check out the code
    - uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install dependencies
    - name: Install dependencies
      working-directory: DummyUIPython
      run: pip install -r requirements.txt

    # Run unit tests with coverage
    - name: Run tests with coverage
      working-directory: DummyUIPython
      run: |
        coverage run -m unittest discover tests
        coverage report --fail-under=80  # Enforce 80% coverage threshold

    # Upload coverage results (optional, for integration with tools like Codecov)
    - name: Upload coverage
      run: coverage xml
